/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThuVienRouteImport } from './routes/thu-vien'
import { Route as LopHocRouteImport } from './routes/lop-hoc'
import { Route as KhoaHocRouteImport } from './routes/khoa-hoc'
import { Route as DeThiThuRouteImport } from './routes/de-thi-thu'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThuVienIndexRouteImport } from './routes/thu-vien.index'
import { Route as LopHocIndexRouteImport } from './routes/lop-hoc.index'
import { Route as ExamPrepIndexRouteImport } from './routes/exam-prep.index'
import { Route as DeThiThuIndexRouteImport } from './routes/de-thi-thu.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ThuVienSlugRouteImport } from './routes/thu-vien.$slug'
import { Route as LopHocSlugRouteImport } from './routes/lop-hoc.$slug'
import { Route as KhoaHocSlugRouteImport } from './routes/khoa-hoc.$slug'
import { Route as ExamPrepSlugRouteImport } from './routes/exam-prep.$slug'
import { Route as DeThiThuSlugRouteImport } from './routes/de-thi-thu.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const ThuVienRoute = ThuVienRouteImport.update({
  id: '/thu-vien',
  path: '/thu-vien',
  getParentRoute: () => rootRouteImport,
} as any)
const LopHocRoute = LopHocRouteImport.update({
  id: '/lop-hoc',
  path: '/lop-hoc',
  getParentRoute: () => rootRouteImport,
} as any)
const KhoaHocRoute = KhoaHocRouteImport.update({
  id: '/khoa-hoc',
  path: '/khoa-hoc',
  getParentRoute: () => rootRouteImport,
} as any)
const DeThiThuRoute = DeThiThuRouteImport.update({
  id: '/de-thi-thu',
  path: '/de-thi-thu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThuVienIndexRoute = ThuVienIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThuVienRoute,
} as any)
const LopHocIndexRoute = LopHocIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LopHocRoute,
} as any)
const ExamPrepIndexRoute = ExamPrepIndexRouteImport.update({
  id: '/exam-prep/',
  path: '/exam-prep/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeThiThuIndexRoute = DeThiThuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeThiThuRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThuVienSlugRoute = ThuVienSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ThuVienRoute,
} as any)
const LopHocSlugRoute = LopHocSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LopHocRoute,
} as any)
const KhoaHocSlugRoute = KhoaHocSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KhoaHocRoute,
} as any)
const ExamPrepSlugRoute = ExamPrepSlugRouteImport.update({
  id: '/exam-prep/$slug',
  path: '/exam-prep/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DeThiThuSlugRoute = DeThiThuSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DeThiThuRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/de-thi-thu': typeof DeThiThuRouteWithChildren
  '/khoa-hoc': typeof KhoaHocRouteWithChildren
  '/lop-hoc': typeof LopHocRouteWithChildren
  '/thu-vien': typeof ThuVienRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/de-thi-thu/$slug': typeof DeThiThuSlugRoute
  '/exam-prep/$slug': typeof ExamPrepSlugRoute
  '/khoa-hoc/$slug': typeof KhoaHocSlugRoute
  '/lop-hoc/$slug': typeof LopHocSlugRoute
  '/thu-vien/$slug': typeof ThuVienSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/de-thi-thu/': typeof DeThiThuIndexRoute
  '/exam-prep/': typeof ExamPrepIndexRoute
  '/lop-hoc/': typeof LopHocIndexRoute
  '/thu-vien/': typeof ThuVienIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/khoa-hoc': typeof KhoaHocRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/de-thi-thu/$slug': typeof DeThiThuSlugRoute
  '/exam-prep/$slug': typeof ExamPrepSlugRoute
  '/khoa-hoc/$slug': typeof KhoaHocSlugRoute
  '/lop-hoc/$slug': typeof LopHocSlugRoute
  '/thu-vien/$slug': typeof ThuVienSlugRoute
  '/blog': typeof BlogIndexRoute
  '/de-thi-thu': typeof DeThiThuIndexRoute
  '/exam-prep': typeof ExamPrepIndexRoute
  '/lop-hoc': typeof LopHocIndexRoute
  '/thu-vien': typeof ThuVienIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/de-thi-thu': typeof DeThiThuRouteWithChildren
  '/khoa-hoc': typeof KhoaHocRouteWithChildren
  '/lop-hoc': typeof LopHocRouteWithChildren
  '/thu-vien': typeof ThuVienRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/de-thi-thu/$slug': typeof DeThiThuSlugRoute
  '/exam-prep/$slug': typeof ExamPrepSlugRoute
  '/khoa-hoc/$slug': typeof KhoaHocSlugRoute
  '/lop-hoc/$slug': typeof LopHocSlugRoute
  '/thu-vien/$slug': typeof ThuVienSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/de-thi-thu/': typeof DeThiThuIndexRoute
  '/exam-prep/': typeof ExamPrepIndexRoute
  '/lop-hoc/': typeof LopHocIndexRoute
  '/thu-vien/': typeof ThuVienIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/de-thi-thu'
    | '/khoa-hoc'
    | '/lop-hoc'
    | '/thu-vien'
    | '/blog/$slug'
    | '/de-thi-thu/$slug'
    | '/exam-prep/$slug'
    | '/khoa-hoc/$slug'
    | '/lop-hoc/$slug'
    | '/thu-vien/$slug'
    | '/blog/'
    | '/de-thi-thu/'
    | '/exam-prep/'
    | '/lop-hoc/'
    | '/thu-vien/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/khoa-hoc'
    | '/blog/$slug'
    | '/de-thi-thu/$slug'
    | '/exam-prep/$slug'
    | '/khoa-hoc/$slug'
    | '/lop-hoc/$slug'
    | '/thu-vien/$slug'
    | '/blog'
    | '/de-thi-thu'
    | '/exam-prep'
    | '/lop-hoc'
    | '/thu-vien'
  id:
    | '__root__'
    | '/'
    | '/de-thi-thu'
    | '/khoa-hoc'
    | '/lop-hoc'
    | '/thu-vien'
    | '/blog/$slug'
    | '/de-thi-thu/$slug'
    | '/exam-prep/$slug'
    | '/khoa-hoc/$slug'
    | '/lop-hoc/$slug'
    | '/thu-vien/$slug'
    | '/blog/'
    | '/de-thi-thu/'
    | '/exam-prep/'
    | '/lop-hoc/'
    | '/thu-vien/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeThiThuRoute: typeof DeThiThuRouteWithChildren
  KhoaHocRoute: typeof KhoaHocRouteWithChildren
  LopHocRoute: typeof LopHocRouteWithChildren
  ThuVienRoute: typeof ThuVienRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  ExamPrepSlugRoute: typeof ExamPrepSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ExamPrepIndexRoute: typeof ExamPrepIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thu-vien': {
      id: '/thu-vien'
      path: '/thu-vien'
      fullPath: '/thu-vien'
      preLoaderRoute: typeof ThuVienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lop-hoc': {
      id: '/lop-hoc'
      path: '/lop-hoc'
      fullPath: '/lop-hoc'
      preLoaderRoute: typeof LopHocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khoa-hoc': {
      id: '/khoa-hoc'
      path: '/khoa-hoc'
      fullPath: '/khoa-hoc'
      preLoaderRoute: typeof KhoaHocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de-thi-thu': {
      id: '/de-thi-thu'
      path: '/de-thi-thu'
      fullPath: '/de-thi-thu'
      preLoaderRoute: typeof DeThiThuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thu-vien/': {
      id: '/thu-vien/'
      path: '/'
      fullPath: '/thu-vien/'
      preLoaderRoute: typeof ThuVienIndexRouteImport
      parentRoute: typeof ThuVienRoute
    }
    '/lop-hoc/': {
      id: '/lop-hoc/'
      path: '/'
      fullPath: '/lop-hoc/'
      preLoaderRoute: typeof LopHocIndexRouteImport
      parentRoute: typeof LopHocRoute
    }
    '/exam-prep/': {
      id: '/exam-prep/'
      path: '/exam-prep'
      fullPath: '/exam-prep/'
      preLoaderRoute: typeof ExamPrepIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de-thi-thu/': {
      id: '/de-thi-thu/'
      path: '/'
      fullPath: '/de-thi-thu/'
      preLoaderRoute: typeof DeThiThuIndexRouteImport
      parentRoute: typeof DeThiThuRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thu-vien/$slug': {
      id: '/thu-vien/$slug'
      path: '/$slug'
      fullPath: '/thu-vien/$slug'
      preLoaderRoute: typeof ThuVienSlugRouteImport
      parentRoute: typeof ThuVienRoute
    }
    '/lop-hoc/$slug': {
      id: '/lop-hoc/$slug'
      path: '/$slug'
      fullPath: '/lop-hoc/$slug'
      preLoaderRoute: typeof LopHocSlugRouteImport
      parentRoute: typeof LopHocRoute
    }
    '/khoa-hoc/$slug': {
      id: '/khoa-hoc/$slug'
      path: '/$slug'
      fullPath: '/khoa-hoc/$slug'
      preLoaderRoute: typeof KhoaHocSlugRouteImport
      parentRoute: typeof KhoaHocRoute
    }
    '/exam-prep/$slug': {
      id: '/exam-prep/$slug'
      path: '/exam-prep/$slug'
      fullPath: '/exam-prep/$slug'
      preLoaderRoute: typeof ExamPrepSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de-thi-thu/$slug': {
      id: '/de-thi-thu/$slug'
      path: '/$slug'
      fullPath: '/de-thi-thu/$slug'
      preLoaderRoute: typeof DeThiThuSlugRouteImport
      parentRoute: typeof DeThiThuRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DeThiThuRouteChildren {
  DeThiThuSlugRoute: typeof DeThiThuSlugRoute
  DeThiThuIndexRoute: typeof DeThiThuIndexRoute
}

const DeThiThuRouteChildren: DeThiThuRouteChildren = {
  DeThiThuSlugRoute: DeThiThuSlugRoute,
  DeThiThuIndexRoute: DeThiThuIndexRoute,
}

const DeThiThuRouteWithChildren = DeThiThuRoute._addFileChildren(
  DeThiThuRouteChildren,
)

interface KhoaHocRouteChildren {
  KhoaHocSlugRoute: typeof KhoaHocSlugRoute
}

const KhoaHocRouteChildren: KhoaHocRouteChildren = {
  KhoaHocSlugRoute: KhoaHocSlugRoute,
}

const KhoaHocRouteWithChildren =
  KhoaHocRoute._addFileChildren(KhoaHocRouteChildren)

interface LopHocRouteChildren {
  LopHocSlugRoute: typeof LopHocSlugRoute
  LopHocIndexRoute: typeof LopHocIndexRoute
}

const LopHocRouteChildren: LopHocRouteChildren = {
  LopHocSlugRoute: LopHocSlugRoute,
  LopHocIndexRoute: LopHocIndexRoute,
}

const LopHocRouteWithChildren =
  LopHocRoute._addFileChildren(LopHocRouteChildren)

interface ThuVienRouteChildren {
  ThuVienSlugRoute: typeof ThuVienSlugRoute
  ThuVienIndexRoute: typeof ThuVienIndexRoute
}

const ThuVienRouteChildren: ThuVienRouteChildren = {
  ThuVienSlugRoute: ThuVienSlugRoute,
  ThuVienIndexRoute: ThuVienIndexRoute,
}

const ThuVienRouteWithChildren =
  ThuVienRoute._addFileChildren(ThuVienRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeThiThuRoute: DeThiThuRouteWithChildren,
  KhoaHocRoute: KhoaHocRouteWithChildren,
  LopHocRoute: LopHocRouteWithChildren,
  ThuVienRoute: ThuVienRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  ExamPrepSlugRoute: ExamPrepSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ExamPrepIndexRoute: ExamPrepIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
